# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaaZi TV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WaaZi TV
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
 pod 'Alamofire'
 pod 'SDWebImage'
 pod 'SwiftyJSON'
 pod 'HydraAsync'
 pod 'LGSideMenuController'
  target 'WaaZi TVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WaaZi TVUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
